# Supabase project configuration
project_id = "eztmmerfuxcgmggewvaq"

[api]
port = 54321
schemas = ["public", "storage", "graphql"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[functions.custom-email-sender]
verify_jwt = false

[functions.business-profile-search]
verify_jwt = false

[functions.business-search]
verify_jwt = false

[functions.foods-list]
verify_jwt = false

[functions.nutrition-calc]
verify_jwt = false
